### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by dkopljar27** [nguyenhoangthuan99/license-plate-recognition#1]
Hey,

I tried to download the dataset from the provided website, but it seems that the web is down.
Can you please upload the dataset to googleDrive or somewhere if you still have it?

Thx

**Comment by Bortrex** [comment]
Hello,

A simple search over the internet might help: [link](https://academictorrents.com/details/8ed33d02d6b36c389dd077ea2478cc83ad117ef3)
